name: "BEHA SmartHeater Bridge"
version: "1.0"
slug: "beha_bridge"
description: "Control BEHA heaters via Home Assistant"
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: services
services:
  - mqtt:need
options:
  beha_email: ""
  beha_password: ""
schema:
  beha_email: str
  beha_password: password
